"""Static configuration: per-table field schemas, intake form configs, admin workflow metadata.

Lives at module scope (not in `create_app`) because it's pure data — the
telegram bot, tests, and routes all import these names directly.
"""

ALLOWED_TABLES = {
    "work_tasks": {
        "fields": [
            "title",
            "cad_skill_area",
            "description",
            "requested_by",
            "request_reference",
            "priority",
            "status",
            "due_date",
            "notes",
            "starter_note",
            "clarifications_needed",
            "software",
            "needs_review",
            "source",
            "ai_raw_input",
            "ai_model",
        ],
        "required": ["title"],
        "label": "CAD Development Task",
        "status_flow": ["Not Started", "In Progress", "On Hold", "Complete"],
    },
    "project_work_tasks": {
        "fields": [
            "project_name",
            "title",
            "project_number",
            "billing_phase",
            "engineer",
            "task_description",
            "priority",
            "status",
            "due_at",
            "notes",
            "needs_review",
            "source",
            "ai_raw_input",
            "ai_model",
        ],
        "required": ["project_name", "title", "project_number", "task_description"],
        "label": "Project Work Task",
        "status_flow": ["Not Started", "In Progress", "On Hold", "Complete"],
    },
    "training_tasks": {
        "fields": [
            "title",
            "trainees",
            "requested_by",
            "skill_area",
            "training_goals",
            "additional_context",
            "priority",
            "status",
            "due_date",
            "notes",
            "needs_review",
            "source",
            "ai_raw_input",
            "ai_model",
        ],
        "required": ["title"],
        "label": "Training Task",
        "status_flow": ["Not Started", "In Progress", "On Hold", "Complete"],
    },
    "personnel_issues": {
        "fields": [
            "person_name",
            "observed_by",
            "cad_skill_area",
            "issue_description",
            "incident_context",
            "recommended_training",
            "severity",
            "status",
            "reported_date",
            "follow_up_date",
            "resolution_notes",
        ],
        "required": ["person_name", "issue_description"],
        "label": "Capability Tracking Entry",
        "status_flow": ["Observed", "Coaching Planned", "Training Scheduled", "Monitoring", "Closed"],
    },
    "suggestion_box": {
        "fields": [
            "title",
            "suggestion_type",
            "submitted_by",
            "submitted_for",
            "summary",
            "expected_value",
            "priority",
            "status",
            "review_notes",
            "promoted_work_task_id",
        ],
        "required": ["title", "summary"],
        "label": "Suggestion",
        "status_flow": ["New", "Under Review", "Approved", "Promoted to CAD", "Declined"],
    },
}

SIMPLE_SUBMISSION_CONFIGS = {
    "cad-development": {
        "table": "work_tasks",
        "source_name": "CAD Request Form",
        "page_title": "CAD Request Submission",
        "heading": "Submit a CAD Request",
        "intro": "Use this form when a CAD-related change, update, fix, or follow-up item should be logged for managers to assign.",
        "submit_label": "Submit CAD Request",
        "success_noun": "CAD request",
        "fields": [
            {"name": "title", "label": "Task Title", "type": "text", "required": True, "placeholder": "Short name for the request"},
            {"name": "requested_by", "label": "Your Name", "type": "text", "required": True, "placeholder": "Jane Smith"},
            {"name": "cad_skill_area", "label": "CAD Skill Area", "type": "text", "placeholder": "Detailing, modeling, standards, templates"},
            {"name": "description", "label": "Requested Change", "type": "textarea", "required": True, "placeholder": "What should be changed or addressed?"},
            {"name": "request_reference", "label": "Context / Follow-up Reference", "type": "textarea", "placeholder": "Who was involved and what context should stay with this request?"},
            {"name": "due_date", "label": "Needed By", "type": "date"},
        ],
    },
    "training": {
        "table": "training_tasks",
        "source_name": "Training Request Form",
        "page_title": "Training Request Submission",
        "heading": "Submit a Training Request",
        "intro": "Use this form to request coaching, training, or learning support that should be tracked as planned work.",
        "submit_label": "Submit Training Request",
        "success_noun": "training request",
        "fields": [
            {"name": "title", "label": "Training Title", "type": "text", "required": True, "placeholder": "Bluebeam markups refresher"},
            {"name": "requested_by", "label": "Your Name", "type": "text", "required": True, "placeholder": "Jane Smith"},
            {"name": "trainees", "label": "Staff Members", "type": "text", "placeholder": "Who needs the training?"},
            {"name": "skill_area", "label": "Skill Area", "type": "text", "placeholder": "Modeling, detailing, standards, automation"},
            {"name": "training_goals", "label": "Training Goals", "type": "textarea", "required": True, "placeholder": "What should be learned or improved?"},
            {"name": "additional_context", "label": "Additional Context", "type": "textarea", "placeholder": "Why is this needed right now?"},
            {"name": "due_date", "label": "Target Date", "type": "date"},
        ],
    },
    "capability": {
        "table": "personnel_issues",
        "source_name": "Capability Observation Form",
        "page_title": "Capability Observation Submission",
        "heading": "Submit a Capability Observation",
        "intro": "Use this form to document a recurring CAD skill gap, process weakness, or coaching need tied to a staff member.",
        "submit_label": "Submit Capability Note",
        "success_noun": "capability note",
        "fields": [
            {"name": "person_name", "label": "Staff Member", "type": "text", "required": True, "placeholder": "Who is this about?"},
            {"name": "observed_by", "label": "Observed By", "type": "text", "required": True, "placeholder": "Your name"},
            {"name": "cad_skill_area", "label": "CAD Skill Area", "type": "text", "placeholder": "Detailing, modeling, standards, revision control"},
            {"name": "issue_description", "label": "Observed Gap / Incident Summary", "type": "textarea", "required": True, "placeholder": "What happened or what gap keeps showing up?"},
            {"name": "incident_context", "label": "Incident Context", "type": "textarea", "placeholder": "What work or situation exposed the issue?"},
            {"name": "recommended_training", "label": "Recommended Training / Follow-Up", "type": "textarea", "placeholder": "What coaching or training would help?"},
        ],
    },
    "suggestion-box": {
        "table": "suggestion_box",
        "source_name": "Suggestion Box Form",
        "page_title": "Suggestion Box Submission",
        "heading": "Submit a Suggestion",
        "intro": "Use this form to suggest training ideas, standards, templates, automation opportunities, or other useful improvements worth reviewing.",
        "submit_label": "Submit Suggestion",
        "success_noun": "suggestion",
        "fields": [
            {"name": "title", "label": "Suggestion Title", "type": "text", "required": True, "placeholder": "Short name for the idea"},
            {"name": "submitted_by", "label": "Your Name", "type": "text", "required": True, "placeholder": "Jane Smith"},
            {"name": "submitted_for", "label": "For Review By", "type": "select", "options": ["Management", "CAD Team", "Training Leads", "Myself", "General Review"]},
            {"name": "suggestion_type", "label": "Suggestion Type", "type": "select", "options": ["Training Idea", "CAD Standard", "Template", "Automation", "Process Improvement", "Tooling", "Other"]},
            {"name": "summary", "label": "Suggestion Summary", "type": "textarea", "required": True, "placeholder": "What is the idea?"},
            {"name": "expected_value", "label": "Why This Would Help", "type": "textarea", "placeholder": "What problem would it solve or improve?"},
        ],
    },
}

ADMIN_WORKFLOW_VIEWS = {
    "project": {
        "title": "Project Work",
        "subtitle": "Manage project-linked execution work with project numbers, billing phase, engineer ownership, and due timing.",
    },
    "work": {
        "title": "CAD Development",
        "subtitle": "Track requested CAD changes, the discipline involved, and the follow-up context behind the work.",
    },
    "training": {
        "title": "Training",
        "subtitle": "Plan and track targeted training work by staff member, skill area, goals, and follow-up context.",
    },
    "personnel": {
        "title": "Capability Tracking",
        "subtitle": "Record observed CAD capability gaps over time so coaching and training needs are visible and traceable.",
    },
    "suggestions": {
        "title": "Suggestion Box",
        "subtitle": "Collect ideas for training, standards, templates, tooling, automation, and process improvements before deciding whether they should become assigned CAD work.",
    },
}
