"""baseline schema (Phase 1D-1)

Revision ID: b580f3481fd9
Revises: 
Create Date: 2026-04-27 06:48:18.199692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b580f3481fd9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.Text(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('field_name', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('old_value', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('new_value', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('user_name', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('approved_emails',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('added_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.Text(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('category', sa.Text(), server_default=sa.text("'Personal'"), nullable=False),
    sa.Column('priority', sa.Text(), server_default=sa.text("'Medium'"), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'Not Started'"), nullable=False),
    sa.Column('due_date', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('recurrence', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('notes', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('source', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personal_tasks', schema=None) as batch_op:
        batch_op.create_index('idx_personal_tasks_completed', ['completed_at'], unique=False)
        batch_op.create_index('idx_personal_tasks_status', ['status'], unique=False)

    op.create_table('personnel_issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_name', sa.Text(), nullable=False),
    sa.Column('observed_by', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('cad_skill_area', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=False),
    sa.Column('incident_context', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('recommended_training', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('severity', sa.Text(), server_default=sa.text("'Medium'"), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'Observed'"), nullable=False),
    sa.Column('reported_date', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('follow_up_date', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('resolution_notes', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_name', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_work_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('project_number', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('billing_phase', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('engineer', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('task_description', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('priority', sa.Text(), server_default=sa.text("'Medium'"), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'Not Started'"), nullable=False),
    sa.Column('due_at', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('notes', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_name', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('needs_review', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('source', sa.Text(), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('ai_raw_input', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('ai_model', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggestion_box',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('suggestion_type', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('submitted_by', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('submitted_for', sa.Text(), server_default=sa.text("'Management'"), nullable=False),
    sa.Column('summary', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('expected_value', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('priority', sa.Text(), server_default=sa.text("'Medium'"), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'New'"), nullable=False),
    sa.Column('review_notes', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('promoted_work_task_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_name', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram_chat_access',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('display_name', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('linked_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('training_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('trainees', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('requested_by', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('skill_area', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('training_goals', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('additional_context', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('priority', sa.Text(), server_default=sa.text("'Medium'"), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'Not Started'"), nullable=False),
    sa.Column('due_date', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('notes', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_name', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('needs_review', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('source', sa.Text(), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('ai_raw_input', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('ai_model', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('role', sa.String(), server_default=sa.text("'user'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('work_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('cad_skill_area', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('requested_by', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('request_reference', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('priority', sa.Text(), server_default=sa.text("'Medium'"), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'Not Started'"), nullable=False),
    sa.Column('due_date', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('notes', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_name', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('starter_note', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('clarifications_needed', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('software', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('needs_review', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('source', sa.Text(), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('ai_raw_input', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('ai_model', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_tasks')
    op.drop_table('users')
    op.drop_table('training_tasks')
    op.drop_table('telegram_chat_access')
    op.drop_table('suggestion_box')
    op.drop_table('project_work_tasks')
    op.drop_table('personnel_issues')
    with op.batch_alter_table('personal_tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_personal_tasks_status')
        batch_op.drop_index('idx_personal_tasks_completed')

    op.drop_table('personal_tasks')
    op.drop_table('comments')
    op.drop_table('approved_emails')
    op.drop_table('app_settings')
    op.drop_table('activity_log')
    # ### end Alembic commands ###
